kind: pipeline
type: docker
name: debio backend v2
trigger:
  branch:
    - development
    - staging
    - main
  event:
    - pull_request

platform:
  os: linux
  arch: amd64

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: whitelist
    host:
      path: /etc/docker/daemon.json
  - name: toolkit
    host:
      path: /data/drone_data

steps:
  - name: verify pull request
    pull: if-not-exists
    image: alpine/git
    volumes:
      - name: toolkit
        path: /data/drone_data
    commands:
      - /data/drone_data/debio_toolkit -approval -repo=debionetwork/debio-backend -id=${DRONE_PULL_REQUEST}
    when:
      branch:
        - main
        - staging
        - development

  - name: build - devel
    pull: if-not-exists
    image: docker
    volumes:
      - name: toolkit
        path: /data/drone_data
      - name: whitelist
        path: /etc/docker/daemon.json
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - /data/drone_data/debio_toolkit -vault -env -secret=debio_development/data/backend_v2
      - docker build -t hub.debio.network/debio_backend_v2_dev:latest .
      - docker push hub.debio.network/debio_backend_v2_dev:latest
    when:
      branch:
        - development

  - name: build - staging
    pull: if-not-exists
    image: docker
    volumes:
      - name: toolkit
        path: /data/drone_data
      - name: whitelist
        path: /etc/docker/daemon.json
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - /data/drone_data/debio_toolkit -vault -env -secret=debio_staging/data/backend_v2
      - docker build -t hub.debio.network/debio_backend_v2_staging:latest .
      - docker push hub.debio.network/debio_backend_v2_staging:latest
    when:
      branch:
        - staging

  - name: build - demo
    pull: if-not-exists
    image: docker
    volumes:
      - name: toolkit
        path: /data/drone_data
      - name: whitelist
        path: /etc/docker/daemon.json
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - /data/drone_data/debio_toolkit -vault -env -secret=debio_production/data/backend_v2
      - docker build -t hub.debio.network/debio_backend_v2_demo:latest .
      - docker push hub.debio.network/debio_backend_v2_demo:latest
    when:
      branch:
        - main

  - name: merge pull request
    pull: if-not-exists
    image: alpine/git
    volumes:
      - name: toolkit
        path: /data/drone_data
    commands:
      - /data/drone_data/debio_toolkit -merge -repo=debionetwork/debio-backend -id=${DRONE_PULL_REQUEST}
    when:
      branch:
        - main
        - staging
        - development

  - name: reload service - devel
    pull: if-not-exists
    image: appleboy/drone-ssh
    volumes:
      - name: toolkit
        path: /data/drone_data
    settings:
      host:
        from_secret: devel_host
      username:
        from_secret: devel_uname
      key_path: /data/drone_data/.ssh/id_rsa
      port: 22
      script:
        - docker stop debio_backend_v2_dev || true && docker rm debio_backend_v2_dev || true
        - docker rmi hub.debio.network/debio_backend_v2_dev:latest
        - docker pull hub.debio.network/debio_backend_v2_dev:latest
        - docker run -d -p 0.0.0.0:4000:4000 --name=debio_backend_v2_dev --env=DEBIOENV=development -v /etc/localtime:/etc/localtime:ro --restart=always hub.debio.network/debio_backend_v2_dev:latest
    when:
      branch:
        - development

  - name: reload service - staging
    pull: if-not-exists
    image: appleboy/drone-ssh
    volumes:
      - name: toolkit
        path: /data/drone_data
    settings:
      host:
        from_secret: stg_host
      username:
        from_secret: stg_uname
      key_path: /data/drone_data/.ssh/id_rsa
      port: 22
      script:
        - docker stop debio_backend_v2_staging || true && docker rm debio_backend_v2_staging || true
        - docker rmi hub.debio.network/debio_backend_v2_staging:latest
        - docker pull hub.debio.network/debio_backend_v2_staging:latest
        - docker run -d --network=host --name=debio_backend_v2_staging --env=DEBIOENV=staging -v /etc/localtime:/etc/localtime:ro --restart=always hub.debio.network/debio_backend_v2_staging:latest
    when:
      branch:
        - staging


  - name: reload service - demo
    pull: if-not-exists
    image: appleboy/drone-ssh
    volumes:
      - name: toolkit
        path: /data/drone_data
    settings:
      host:
        from_secret: stg_host
      username:
        from_secret: stg_uname
      key_path: /data/drone_data/.ssh/id_rsa
      port: 22
      script:
        - docker stop debio_backend_v2_demo || true && docker rm debio_backend_v2_demo || true
        - docker rmi hub.debio.network/debio_backend_v2_demo:latest
        - docker pull hub.debio.network/debio_backend_v2_demo:latest
        - docker run -d --network=host --name=debio_backend_v2_demo --env=DEBIOENV=production -v /etc/localtime:/etc/localtime:ro --restart=always hub.debio.network/debio_backend_v2_demo:latest
    when:
      branch:
        - main

  - name: notify deployment
    image: appleboy/drone-discord
    pull: if-not-exists
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: >
        {{#success build.status}}
        ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.

        📝 Commit by {{commit.author}} on

        `{{commit.branch}}`:

        ```
        {{commit.message}}
        ```

        🌐 {{ build.link }}
        {{else}}
        ❌ Build #{{build.number}} of `{{repo.name}}` failed.

        📝 Commit by {{commit.author}} on

        `{{commit.branch}}`:

        ```
        {{commit.message}}
        ```
        🌐 {{ build.link }}
        🌐 {{ commit.link }}
        {{/success}}
    when:
      status: [ success, failure ]
      branch:
        - main
        - staging
        - development


---
kind: secret
name: devel_host
get:
  path: drone_development/deploy_target
  name: devel_host
---
kind: secret
name: devel_key
get:
  path: drone_development/deploy_target
  name: devel_key
---
kind: secret
name: devel_uname
get:
  path: drone_development/deploy_target
  name: devel_uname
---
kind: secret
name: stg_host
get:
  path: drone_staging/deploy_target
  name: stg_host
---
kind: secret
name: stg_key
get:
  path: drone_staging/deploy_target
  name: stg_key
---
kind: secret
name: stg_uname
get:
  path: drone_staging/deploy_target
  name: stg_uname
---
kind: secret
name: discord_id
get:
  path: drone_common_config/webhook
  name: discord_id
---
kind: secret
name: discord_token
get:
  path: drone_common_config/webhook
  name: discord_token