version: '3'

services:
  web:
    container_name: debio-backend
    image: debionetwork/debio-backend
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 3003:3000
    networks:
      debio:
        ipv4_address: 172.27.1.13
        aliases:
          - debio-backend

networks:
  debio:
    external: true
