export enum TransactionStatusList {
  Cancelled = 'Cancelled',
  CustomerAddDataAsBounty = 'Customer Add Data as Bounty',
  CustomerStakeRequestService = 'Customer Stake Request Service',
  Excess = 'Excess',
  Failed = 'Failed',
  Finalized = 'Finalized',
  Fulfilled = 'Fulfilled',
  LabProvideRequestedService = 'Lab Provide Requested Service',
  LabVerified = 'Lab Verified',
  Paid = 'Paid',
  Partial = 'Partial',
  Refunded = 'Refunded',
  RegisteredUser = 'Registered User',
  Rejected = 'Rejected',
  Revoked = 'Revoked',
  ServiceCharge = 'Service Charge',
  Stake = 'Stake',
  Staked = 'Staked',
  Unpaid = 'Unpaid',
  Unstake = 'Unstake',
  Unstaked = 'Unstaked',
  Unverified = 'Unverified',
  Verified = 'Verified',
  WaitingForUnstake = 'Waiting For Unstake',
  WaitingForUnstaked = 'Waiting For Unstaked',
}
