{{- if and .Values.config.postgres.host .Values.config.postgres.username .Values.config.postgres.password .Values.config.postgres.dbname }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.postgresSecretName" . }}
type: Opaque
data:
  host: {{ .Values.config.postgres.host | b64enc }}
  username: {{ .Values.config.postgres.username | b64enc }}
  password: {{ .Values.config.postgres.password | b64enc }}
  dbname: {{ .Values.config.postgres.dbname | b64enc }}

---
{{- end }}
{{- if .Values.config.postgres.dbCity }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.dbCitySecretName" . }}
type: Opaque
data:
  dbCity: {{ .Values.config.postgres.dbCity | b64enc }}

---
{{- end }}
{{- if .Values.config.postgres.dbLocations }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.dbLocationsSecretName" . }}
type: Opaque
data:
  dbLocations: {{ .Values.config.postgres.dbLocations | b64enc }}

---
{{- end }}
{{- if .Values.config.adminSubstrateMnemonic }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.adminSubstrateMnemonicSecretName" . }}
type: Opaque
data:
  adminSubstrateMnemonic: {{ .Values.config.adminSubstrateMnemonic | b64enc }}

---
{{- end }}
{{- if .Values.config.debioEscrowPrivateKey }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.debioEscrowPrivateKeySecretName" . }}
type: Opaque
data:
  debioEscrowPrivateKey: {{ .Values.config.debioEscrowPrivateKey | b64enc }}

---
{{- end }}
{{- if .Values.config.escrowContractAddress }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.escrowContractAddressSecretName" . }}
type: Opaque
data:
  escrowContractAddress: {{ .Values.config.escrowContractAddress | b64enc }}

---
{{- end }}
{{- if .Values.config.coinmarketcapApiKey }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.coinmarketcapApiKeySecretName" . }}
type: Opaque
data:
  coinmarketcapApiKey: {{ .Values.config.coinmarketcapApiKey | b64enc }}

---
{{- end }}
{{- if .Values.config.recaptchaSecretKey }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.recaptchaSecretKeySecretName" . }}
type: Opaque
data:
  recaptchaSecretKey: {{ .Values.config.recaptchaSecretKey | b64enc }}

---
{{- end }}
{{- if .Values.config.debioApiKey }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.debioApiKeySecretName" . }}
type: Opaque
data:
  debioApiKey: {{ .Values.config.debioApiKey | b64enc }}

---
{{- end }}
{{- if .Values.config.elastic.node }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.elasticNodeSecretName" . }}
type: Opaque
data:
  node: {{ .Values.config.elastic.node | b64enc }}

---
{{- end }}
{{- if .Values.config.elastic.username }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.elasticUsernameSecretName" . }}
type: Opaque
data:
  username: {{ .Values.config.elastic.username | b64enc }}

---
{{- end }}
{{- if .Values.config.elastic.password }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.elasticPasswordSecretName" . }}
type: Opaque
data:
  password: {{ .Values.config.elastic.password | b64enc }}

---
{{- end }}
{{- if and .Values.config.email.email .Values.config.email.password .Values.config.email.emails }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.emailSecretName" . }}
type: Opaque
data:
  email: {{ .Values.config.email.email | b64enc }}
  password: {{ .Values.config.email.password | b64enc }}
  emails: {{ .Values.config.email.emails | b64enc }}

---
{{- end }}
{{- if .Values.config.bucketname }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.bucketnameSecretName" . }}
type: Opaque
data:
  bucketname: {{ .Values.config.bucketname | b64enc }}

---
{{- end }}
{{- if .Values.config.storageBaseURI }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.storageBaseURISecretName" . }}
type: Opaque
data:
  storageBaseURI: {{ .Values.config.storageBaseURI | b64enc }}

---
{{- end }}
{{- if .Values.config.google.serviceAccountBase64 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-backend.serviceAccountSecretName" . }}
type: Opaque
data:
  serviceAccount: {{ .Values.config.google.serviceAccountBase64 }}

{{- end }}
