name: Alpha automation

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-alpha*'

concurrency:
  group: alpha-automation

jobs:
  compute-build-info:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.build-info.outputs.latest_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compute build info
        id: build-info
        shell: bash
        run: |
          version=${GITHUB_REF#refs/*/}
          echo $version
          echo "::set-output name=latest_tag::$version"

  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    needs: compute-build-info
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.STG_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.STG_GCP_SA_KEY }}
          export_default_credentials: true
      - name: Get secrets
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            SWAGGER_ENABLE:${{ secrets.STG_GCP_PROJECT_ID }}/SWAGGER_ENABLE
            PORT:${{ secrets.STG_GCP_PROJECT_ID }}/PORT
            POSTGRES_HOST:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_HOST
            POSTGRES_USERNAME:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_USERNAME
            POSTGRES_PASSWORD:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_PASSWORD
            POSTGRES_DB:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_DB
            POSTGRES_DB_CITY:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_DB_CITY
            POSTGRES_DB_LOCATIONS:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_DB_LOCATIONS
            SUBSTRATE_URL:${{ secrets.STG_GCP_PROJECT_ID }}/SUBSTRATE_URL            
            ADMIN_SUBSTRATE_MNEMONIC:${{ secrets.STG_GCP_PROJECT_ID }}/ADMIN_SUBSTRATE_MNEMONIC                        
            WEB3_RPC:${{ secrets.STG_GCP_PROJECT_ID }}/WEB3_RPC
            WEB3_RPC_HTTPS:${{ secrets.STG_GCP_PROJECT_ID }}/WEB3_RPC_HTTPS
            DEBIO_ESCROW_PRIVATE_KEY:${{ secrets.STG_GCP_PROJECT_ID }}/DEBIO_ESCROW_PRIVATE_KEY
            ESCROW_CONTRACT_ADDRESS:${{ secrets.STG_GCP_PROJECT_ID }}/ESCROW_CONTRACT_ADDRESS            
            COINMARKETCAP_API_KEY:${{ secrets.STG_GCP_PROJECT_ID }}/COINMARKETCAP_API_KEY
            RECAPTCHA_SECRET_KEY:${{ secrets.STG_GCP_PROJECT_ID }}/RECAPTCHA_SECRET_KEY
            DEBIO_API_KEY:${{ secrets.STG_GCP_PROJECT_ID }}/DEBIO_API_KEY
            ELASTICSEARCH_NODE:${{ secrets.STG_GCP_PROJECT_ID }}/ELASTICSEARCH_NODE
            ELASTICSEARCH_USERNAME:${{ secrets.STG_GCP_PROJECT_ID }}/ELASTICSEARCH_USERNAME
            ELASTICSEARCH_PASSWORD:${{ secrets.STG_GCP_PROJECT_ID }}/ELASTICSEARCH_PASSWORD
            REDIS_STORE_URL:${{ secrets.STG_GCP_PROJECT_ID }}/REDIS_STORE_URL
            REDIS_STORE_USERNAME:${{ secrets.STG_GCP_PROJECT_ID }}/REDIS_STORE_USERNAME
            REDIS_STORE_PASSWORD:${{ secrets.STG_GCP_PROJECT_ID }}/REDIS_STORE_PASSWORD
            EMAIL:${{ secrets.STG_GCP_PROJECT_ID }}/EMAIL
            PASS_EMAIL:${{ secrets.STG_GCP_PROJECT_ID }}/PASS_EMAIL
            EMAILS:${{ secrets.STG_GCP_PROJECT_ID }}/EMAILS
            BUCKET_NAME:${{ secrets.STG_GCP_PROJECT_ID }}/BUCKET_NAME
            STORAGE_BASE_URI:${{ secrets.STG_GCP_PROJECT_ID }}/STORAGE_BASE_URI
            GOOGLE_APPLICATION_CREDENTIALS:${{ secrets.STG_GCP_PROJECT_ID }}/GOOGLE_APPLICATION_CREDENTIALS
            API_HEALTHCHECK:${{ secrets.STG_GCP_PROJECT_ID }}/API_HEALTHCHECK
            API_HEALTHCHECK_URL:${{ secrets.STG_GCP_PROJECT_ID }}/API_HEALTHCHECK_URL
            SSH_HOST:${{ secrets.STG_GCP_PROJECT_ID }}/SSH_HOST
            SSH_USERNAME:${{ secrets.STG_GCP_PROJECT_ID }}/SSH_USERNAME
            SSH_KEY:${{ secrets.STG_GCP_PROJECT_ID }}/SSH_KEY
            SSH_PORT:${{ secrets.STG_GCP_PROJECT_ID }}/SSH_PORT
      - name: Create .env & gcp sa
        shell: bash
        run: |
          tee -a .env <<EOF
          SWAGGER_ENABLE=${{ steps.secrets.outputs.SWAGGER_ENABLE }}
          PORT=${{ steps.secrets.outputs.PORT }}
          HOST_POSTGRES=${{ steps.secrets.outputs.POSTGRES_HOST }}
          USERNAME_POSTGRES=${{ steps.secrets.outputs.POSTGRES_USERNAME }}
          PASSWORD_POSTGRES=${{ steps.secrets.outputs.POSTGRES_PASSWORD }}
          DB_POSTGRES=${{ steps.secrets.outputs.POSTGRES_DB }}
          DB_CITY=${{ steps.secrets.outputs.POSTGRES_DB_CITY }}
          DB_LOCATIONS=${{ steps.secrets.outputs.POSTGRES_DB_LOCATIONS }}
          SUBSTRATE_URL=${{ steps.secrets.outputs.SUBSTRATE_URL }}          
          ADMIN_SUBSTRATE_MNEMONIC=${{ steps.secrets.outputs.ADMIN_SUBSTRATE_MNEMONIC }}                    
          WEB3_RPC=${{ steps.secrets.outputs.WEB3_RPC }}
          WEB3_RPC_HTTPS=${{ steps.secrets.outputs.WEB3_RPC_HTTPS }}
          DEBIO_ESCROW_PRIVATE_KEY=${{ steps.secrets.outputs.DEBIO_ESCROW_PRIVATE_KEY }}          
          ESCROW_CONTRACT_ADDRESS=${{ steps.secrets.outputs.ESCROW_CONTRACT_ADDRESS }}          
          COINMARKETCAP_API_KEY=${{ steps.secrets.outputs.COINMARKETCAP_API_KEY }}
          RECAPTCHA_SECRET_KEY=${{ steps.secrets.outputs.RECAPTCHA_SECRET_KEY }}
          DEBIO_API_KEY=${{ steps.secrets.outputs.DEBIO_API_KEY }}
          ELASTICSEARCH_NODE=${{ steps.secrets.outputs.ELASTICSEARCH_NODE }}
          ELASTICSEARCH_USERNAME=${{ steps.secrets.outputs.ELASTICSEARCH_USERNAME }}
          ELASTICSEARCH_PASSWORD=${{ steps.secrets.outputs.ELASTICSEARCH_PASSWORD }}
          REDIS_STORE_URL=${{ steps.secrets.outputs.REDIS_STORE_URL }}
          REDIS_STORE_USERNAME=${{ steps.secrets.outputs.REDIS_STORE_USERNAME }}
          REDIS_STORE_PASSWORD=${{ steps.secrets.outputs.REDIS_STORE_PASSWORD }}
          EMAIL=${{ steps.secrets.outputs.EMAIL }}
          PASS_EMAIL=${{ steps.secrets.outputs.PASS_EMAIL }}
          EMAILS=${{ steps.secrets.outputs.EMAILS }}
          BUCKET_NAME=${{ steps.secrets.outputs.BUCKET_NAME }}
          STORAGE_BASE_URI=${{ steps.secrets.outputs.STORAGE_BASE_URI }}
          BACKEND_HEALTHCHECK_URL=${{ steps.secrets.outputs.API_HEALTHCHECK_URL }}
          EOF
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-main
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.STG_GCP_SA_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: .maintain/docker/Dockerfile
          tags: |
            gcr.io/${{ secrets.STG_GCP_PROJECT_ID }}/${{ github.repository }}:${{ needs.compute-build-info.outputs.latest_tag }}
            gcr.io/${{ secrets.STG_GCP_PROJECT_ID }}/${{ github.repository }}:latest-alpha
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  publish-draft-release:
    runs-on: ubuntu-latest
    needs: [build-and-publish-docker-image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: '.github/workflows/rcb_config.json'
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: true
          prerelease: true

  deploy:
    runs-on: ubuntu-latest
    needs: [compute-build-info, publish-draft-release]
    env:
      DEPLOY: ${{ secrets.STG_DEPLOY }}
    steps:
      - name: Checkout code
        if: "${{ env.DEPLOY == 'true' }}"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        if: "${{ env.DEPLOY == 'true' }}"
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.STG_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.STG_GCP_SA_KEY }}
          export_default_credentials: true
      - name: Get secrets
        if: "${{ env.DEPLOY == 'true' }}"
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            SWAGGER_ENABLE:${{ secrets.STG_GCP_PROJECT_ID }}/SWAGGER_ENABLE
            PORT:${{ secrets.STG_GCP_PROJECT_ID }}/PORT
            POSTGRES_HOST:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_HOST
            POSTGRES_USERNAME:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_USERNAME
            POSTGRES_PASSWORD:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_PASSWORD
            POSTGRES_DB:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_DB
            POSTGRES_DB_CITY:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_DB_CITY
            POSTGRES_DB_LOCATIONS:${{ secrets.STG_GCP_PROJECT_ID }}/POSTGRES_DB_LOCATIONS
            SUBSTRATE_URL:${{ secrets.STG_GCP_PROJECT_ID }}/SUBSTRATE_URL            
            ADMIN_SUBSTRATE_MNEMONIC:${{ secrets.STG_GCP_PROJECT_ID }}/ADMIN_SUBSTRATE_MNEMONIC                        
            WEB3_RPC:${{ secrets.STG_GCP_PROJECT_ID }}/WEB3_RPC
            WEB3_RPC_HTTPS:${{ secrets.STG_GCP_PROJECT_ID }}/WEB3_RPC_HTTPS
            DEBIO_ESCROW_PRIVATE_KEY:${{ secrets.STG_GCP_PROJECT_ID }}/DEBIO_ESCROW_PRIVATE_KEY
            ESCROW_CONTRACT_ADDRESS:${{ secrets.STG_GCP_PROJECT_ID }}/ESCROW_CONTRACT_ADDRESS            
            COINMARKETCAP_API_KEY:${{ secrets.STG_GCP_PROJECT_ID }}/COINMARKETCAP_API_KEY
            RECAPTCHA_SECRET_KEY:${{ secrets.STG_GCP_PROJECT_ID }}/RECAPTCHA_SECRET_KEY
            DEBIO_API_KEY:${{ secrets.STG_GCP_PROJECT_ID }}/DEBIO_API_KEY
            ELASTICSEARCH_NODE:${{ secrets.STG_GCP_PROJECT_ID }}/ELASTICSEARCH_NODE
            ELASTICSEARCH_USERNAME:${{ secrets.STG_GCP_PROJECT_ID }}/ELASTICSEARCH_USERNAME
            ELASTICSEARCH_PASSWORD:${{ secrets.STG_GCP_PROJECT_ID }}/ELASTICSEARCH_PASSWORD
            REDIS_STORE_URL:${{ secrets.STG_GCP_PROJECT_ID }}/REDIS_STORE_URL
            REDIS_STORE_USERNAME:${{ secrets.STG_GCP_PROJECT_ID }}/REDIS_STORE_USERNAME
            REDIS_STORE_PASSWORD:${{ secrets.STG_GCP_PROJECT_ID }}/REDIS_STORE_PASSWORD
            EMAIL:${{ secrets.STG_GCP_PROJECT_ID }}/EMAIL
            PASS_EMAIL:${{ secrets.STG_GCP_PROJECT_ID }}/PASS_EMAIL
            EMAILS:${{ secrets.STG_GCP_PROJECT_ID }}/EMAILS
            BUCKET_NAME:${{ secrets.STG_GCP_PROJECT_ID }}/BUCKET_NAME
            STORAGE_BASE_URI:${{ secrets.STG_GCP_PROJECT_ID }}/STORAGE_BASE_URI
            GOOGLE_APPLICATION_CREDENTIALS:${{ secrets.STG_GCP_PROJECT_ID }}/GOOGLE_APPLICATION_CREDENTIALS
            API_HEALTHCHECK:${{ secrets.STG_GCP_PROJECT_ID }}/API_HEALTHCHECK
            API_HEALTHCHECK_URL:${{ secrets.STG_GCP_PROJECT_ID }}/API_HEALTHCHECK_URL
            SSH_HOST:${{ secrets.STG_GCP_PROJECT_ID }}/SSH_HOST
            SSH_USERNAME:${{ secrets.STG_GCP_PROJECT_ID }}/SSH_USERNAME
            SSH_KEY:${{ secrets.STG_GCP_PROJECT_ID }}/SSH_KEY
            SSH_PORT:${{ secrets.STG_GCP_PROJECT_ID }}/SSH_PORT
      - name: Deploy
        if: "${{ env.DEPLOY == 'true' }}"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.secrets.outputs.SSH_HOST }}
          username: ${{ steps.secrets.outputs.SSH_USERNAME }}
          key: ${{ steps.secrets.outputs.SSH_KEY }}
          port: ${{ steps.secrets.outputs.SSH_PORT }}
          script: |
            ./connect.sh
            helm repo add debio https://charts.debio.network
            helm repo update
            helm upgrade debio-backend debio/debio-backend \
              --install \
              --set-string image.repository=gcr.io/${{ secrets.STG_GCP_PROJECT_ID }}/${{ github.repository }} \
              --set-string image.tag=${{ needs.compute-build-info.outputs.latest_tag }} \
              --set-string imagePullSecrets[0].name=gcr-auth \
              --set-string config.swagger.enable=${{ steps.secrets.outputs.SWAGGER_ENABLE }} \
              --set-string config.port=${{ steps.secrets.outputs.PORT }} \
              --set-string config.postgres.host=${{ steps.secrets.outputs.POSTGRES_HOST }} \
              --set-string config.postgres.username=${{ steps.secrets.outputs.POSTGRES_USERNAME }} \
              --set-string config.postgres.password=${{ steps.secrets.outputs.POSTGRES_PASSWORD }} \
              --set-string config.postgres.dbname=${{ steps.secrets.outputs.POSTGRES_DB }} \
              --set-string config.postgres.dbCity=${{ steps.secrets.outputs.POSTGRES_DB_CITY }} \
              --set-string config.postgres.dbLocations=${{ steps.secrets.outputs.POSTGRES_DB_LOCATIONS }} \
              --set-string config.substrateURL=${{ steps.secrets.outputs.SUBSTRATE_URL }} \
              --set-string config.adminSubstrateMnemonic="${{ steps.secrets.outputs.ADMIN_SUBSTRATE_MNEMONIC }}" \
              --set-string config.web3RPC=${{ steps.secrets.outputs.WEB3_RPC }} \
              --set-string config.web3RPCHttps=${{ steps.secrets.outputs.WEB3_RPC_HTTPS }} \
              --set-string config.debioEscrowPrivateKey=${{ steps.secrets.outputs.DEBIO_ESCROW_PRIVATE_KEY }} \
              --set-string config.escrowContractAddress=${{ steps.secrets.outputs.ESCROW_CONTRACT_ADDRESS }} \
              --set-string config.coinmarketcapApiKey="${{ steps.secrets.outputs.COINMARKETCAP_API_KEY }}" \
              --set-string config.recaptchaSecretKey=${{ steps.secrets.outputs.RECAPTCHA_SECRET_KEY }} \
              --set-string config.debioApiKey=${{ steps.secrets.outputs.DEBIO_API_KEY }} \
              --set-string config.elastic.node=${{ steps.secrets.outputs.ELASTICSEARCH_NODE }} \
              --set-string config.elastic.username=${{ steps.secrets.outputs.ELASTICSEARCH_USERNAME }} \
              --set-string config.elastic.password=${{ steps.secrets.outputs.ELASTICSEARCH_PASSWORD }} \
              --set-string config.redis.url=${{ steps.secrets.outputs.REDIS_STORE_URL }} \
              --set-string config.redis.username=${{ steps.secrets.outputs.REDIS_STORE_USERNAME }} \
              --set-string config.redis.password=${{ steps.secrets.outputs.REDIS_STORE_PASSWORD }} \
              --set-string config.email.email=${{ steps.secrets.outputs.EMAIL }} \
              --set-string config.email.password=${{ steps.secrets.outputs.PASS_EMAIL }} \
              --set-string config.email.emails="${{ steps.secrets.outputs.EMAILS }}" \
              --set-string config.bucketname=${{ steps.secrets.outputs.BUCKET_NAME }} \
              --set-string config.storageBaseURI=${{ steps.secrets.outputs.STORAGE_BASE_URI }} \
              --set-string config.google.serviceAccountBase64=${{ steps.secrets.outputs.GOOGLE_APPLICATION_CREDENTIALS }} \
              --set-string config.healthcheck={{ steps.secrets.outputs.API_HEALTHCHECK_URL }} \
              --set-string config.startupProbe.path=${{ steps.secrets.outputs.API_HEALTHCHECK }} \
              --set-string config.livenessProbe.path=${{ steps.secrets.outputs.API_HEALTHCHECK }} \
              --set-string config.readinessProbe.path=${{ steps.secrets.outputs.API_HEALTHCHECK }} \
              --set ingress.enabled=true \
              --set-string ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
              --set-string ingress.annotations."cert-manager\.io/cluster-issuer"=letsencrypt \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/limit-rps"="100" \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/rewrite-target"=/\$2\$3 \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/auth-type"="basic" \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/auth-secret"="auth-fe" \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/auth-realm"="Authentication Required" \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/enable-cors"="true" \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/cors-allow-methods"="GET\, PUT\, POST\, DELETE\, PATCH\, OPTIONS" \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/cors-allow-headers"="Origin\,DNT\,X-CustomHeader\,Keep-Alive\,User-Agent\,X-Requested-With\,If-Modified-Since\,Cache-Control\,Content-Type\,Authorization\,Accept\,debio-api-key" \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/cors-allow-origin"="https://app.stg.debio.network\, https://lab.stg.debio.network" \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/cors-allow-credentials"="true" \
              --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/cors-max-age"="600" \
              --set-string ingress.hosts[0].host=api.stg.debio.network \
              --set-string ingress.hosts[0].paths[0].path=/\(\)\(.\*\) \
              --set-string ingress.hosts[0].paths[0].pathType=Prefix \
              --set-string ingress.hosts[0].paths[1].path=/conversion/\(\)\(.\*\) \
              --set-string ingress.hosts[0].paths[1].pathType=Prefix \
              --set-string ingress.hosts[0].paths[1].serviceName=debio-conversion \
              --set-string ingress.hosts[0].paths[1].servicePort=80 \
              --set-string ingress.tls[0].secretName=debio-backend-tls \
              --set-string ingress.tls[0].hosts[0]=api.stg.debio.network \
              --set-string resources.requests.cpu=300m \
              --set-string resources.requests.memory=512Mi \
              --set-string resources.limits.cpu=500m \
              --set-string resources.limits.memory=1024Mi \
              --set replicaCount=3 \
              --set autoscaling.enabled=true \
              --set autoscaling.minReplicas=3 \
              --set autoscaling.maxReplicas=20
            kubectl rollout status deployment/debio-backend
