name: Analyzer

on:
  branch_protection_rule:
  pull_request:
    branches:
      - main
      - releases/**
  push:
    branches:
      - main
      - releases/**
  schedule:
    - cron: '00 5 * * 0'

concurrency:
  group: analyzer-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  security-cii-best-practice:
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      id-token: write
      security-events: write
    runs-on: ubuntu-20.04
    name: Security CII Best Practices
    steps:
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Perform Scorecards Analysis
        uses: ossf/scorecard-action@e363bfca00e752f91de7b7d2a77340e2e523cb18 # v2.0.4
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: Upload artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: Upload to Code-Scanning
        uses: github/codeql-action/upload-sarif@e0e5ded33cabb451ae0a9768fc7b0410bad9ad44 # v2.1.26
        with:
          sarif_file: results.sarif

  security-sast:
    if: ${{ github.event_name != 'branch_protection_rule' && github.event_name != 'push' }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ javascript, typescript ]
    runs-on: ubuntu-20.04
    name: Security Static Code Analysis for ${{ matrix.language }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@e0e5ded33cabb451ae0a9768fc7b0410bad9ad44 # v2.1.26
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@e0e5ded33cabb451ae0a9768fc7b0410bad9ad44 # v2.1.26
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@e0e5ded33cabb451ae0a9768fc7b0410bad9ad44 # v2.1.26

  dead-link:
    if: ${{ github.event_name != 'branch_protection_rule' && github.event_name != 'push' }}
    runs-on: ubuntu-20.04
    name: Dead Link
    steps:
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          fetch-depth: 0
      - name: Perform Markdown Dead Link Analysis
        uses: gaurav-nelson/github-action-markdown-link-check@9710f0fec812ce0a3b98bef4c9d842fc1f39d976 # 1.0.13
        with:
          use-quiet-mode: yes
          config-file: ./.github/workflows/mlc_config.json
