name: Analyzer

on:
  branch_protection_rule:
  pull_request:
    branches:
      - main
      - releases/**
  push:
    branches:
      - main
      - releases/**
  schedule:
    - cron: '00 5 * * 0'

concurrency:
  group: analyzer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-cii-best-practice:
    if: ${{ !startsWith(github.ref, 'refs/pull/') }}
    runs-on: ubuntu-20.04
    permissions:
      security-events: write
      id-token: write
      actions: read
      contents: read
    name: Security CII Best Practices
    steps:
      - name: Checkout Repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
        with:
          persist-credentials: false
      - name: Perform Scorecards Analysis
        uses: ossf/scorecard-action@3e15ea8318eee9b333819ec77a36aca8d39df13e # tag=v1.1.1
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true
      - name: Upload artifact
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: Upload to Code-Scanning
        uses: github/codeql-action/upload-sarif@5f532563584d71fdef14ee64d17bafb34f751ce5 # tag=v1.0.26
        with:
          sarif_file: results.sarif

  security-sast:
    if: ${{ !startsWith(github.ref, 'refs/heads/') }}
    runs-on: ubuntu-20.04
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'typescript' ]
    name: Security Static Code Analysis for ${{ matrix.language }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  check-dead-link:
    if: ${{ !startsWith(github.ref, 'refs/heads/') }}
    runs-on: ubuntu-20.04
    name: Check Dead Link
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Perform Check Dead Link on Markdown
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/workflows/mlc_config.json"
