name: Builder

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

concurrency:
  group: builder

jobs:
  start-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.DEV_GOOGLE_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.DEV_SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: start runner
        run: gcloud compute instances start gh-runner --zone=asia-southeast1-b

  integration-testing:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create .env and service account file
        shell: bash
        run: |
          tee -a .env <<EOF
          ${{ secrets.IT_ENV }}
          EOF

          tee -a service-account-file.json <<EOF
          ${{ secrets.IT_SA_JSON }}
          EOF
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Run Integration Tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./service-account-file.json
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: npm run test:e2e

  compute-build-info:
    runs-on: self-hosted
    needs:
      - integration-testing
    outputs:
      sha_short: ${{ steps.build-info.outputs.sha_short }}
      revision_tag: ${{ steps.build-info.outputs.revision_tag }}
      latest_tag: ${{ steps.build-info.outputs.latest_tag }}
      pre_release: ${{ steps.build-info.outputs.pre_release }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Compute build info
        id: build-info
        shell: bash
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          REVISION_TAG=$SHA_SHORT
          LATEST_TAG=latest-pre-alpha
          PRE_RELEASE=true

          if [[ $GITHUB_REF =~ refs/tags/ ]] ;
          then
            TAG=${GITHUB_REF#refs/tags/}
            VERSION=${TAG%.*}.$((${TAG##*.}))
            REVISION_TAG=$TAG

            if [[ $TAG =~ [0-9]+.[0-9]+.[0-9]+$ ]] ;
            then
                LATEST_TAG=latest
                PRE_RELEASE=false
            else
                SUFFIX=$(tmp=${TAG#$VERSION-} ; echo $tmp | sed -r 's/[0-9]//g' )
                LATEST_TAG=latest-$SUFFIX
            fi
          fi
          echo "::set-output name=sha_short::$SHA_SHORT"
          echo "::set-output name=revision_tag::$REVISION_TAG"
          echo "::set-output name=latest_tag::$LATEST_TAG"
          echo "::set-output name=pre_release::$PRE_RELEASE"

  build:
    runs-on: self-hosted
    needs:
      - compute-build-info
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-main
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .maintain/docker/Dockerfile
          tags: |
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.revision_tag }}
            ${{ github.repository }}:${{ needs.compute-build-info.outputs.latest_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      # publish-draft-release
      - name: Build changelog
        if: "startsWith(github.ref, 'refs/tags/')"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: '.github/workflows/rcb_config.json'
      - name: Create draft release
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: true
          prerelease: ${{ needs.compute-build-info.outputs.pre_release }}

  stop-runner:
    runs-on: self-hosted
    needs: [start-runner, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.DEV_GOOGLE_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.DEV_SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: stop runner
        run: gcloud compute instances stop gh-runner --zone=asia-southeast1-b
