name: Integration Tester Automation

on:
  issue_comment:
    types:
    - created

concurrency:
  group: it-e2e-tester-${{ github.event.pull_request.number }}

jobs:
  start-runner:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/it'}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: start runner
        run: gcloud compute instances start github-runner --zone=asia-southeast1-b
        
  testing:
    runs-on: [self-hosted]
    needs: [start-runner]
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/it'}}
    environment: development
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create .env File
        shell: bash
        run: |
          tee -a .env <<EOF
          ${{ secrets.FULL_ENV }}
          EOF
      - name: Create service-account-file.json File
        shell: bash
        run: |
          tee -a service-account-file.json <<EOF
          ${{ secrets.SERVICE_ACCOUNT_FILE_JSON }}
          EOF
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Run Integration Tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./service-account-file.json
        run: npm run test:e2e

  stop-runner:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/it'}}
    needs: [testing]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: stop runner
        run: gcloud compute instances stop github-runner --zone=asia-southeast1-b
