name: SAST

on:
  pull_request:
  schedule:
    - cron: '00 5 * * 0'

permissions:
  contents: read

concurrency:
  group: sast-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript
          - typescript
    runs-on: ubuntu-20.04
    name: CodeQL ( ${{ matrix.language }} )
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Initialize
        uses: github/codeql-action/init@807578363a7869ca324a79039e6db9c843e0e100
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@807578363a7869ca324a79039e6db9c843e0e100
      - name: Analize
        uses: github/codeql-action/analyze@807578363a7869ca324a79039e6db9c843e0e100
