name: Tester

on:
  pull_request:
    branches:
      - main
      - releases/**

concurrency:
  group: tester-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-20.04
    name: Testing on Node.js 16
    steps:
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          fetch-depth: 0
      - name: Set Up Node.js
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # v3.5.0
        with:
          node-version: 16
      - name: Install Dependencies
        if: steps.dependencies-cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - name: Check Lint
        run: npm run lint:check
      - name: Check Format
        run: npm run format:check
      - name: Run Unit Test
        run: npm run test:unit
      - name: Run Build
        run: npm run build
