name: Tester

on:
  pull_request_target:
    branches:
      - main

concurrency:
  group: tester-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create .env and sa file
        shell: bash
        run: |
          tee -a .env <<EOF
          ${{ secrets.IT_ENV }}
          EOF

          tee -a service-account-file.json <<EOF
          ${{ secrets.IT_SA_JSON }}
          EOF
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Run Unit Tests
        run: npm run test
      - name: Run Integration Tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./service-account-file.json
        run: npm run test:e2e
      - name: Run Build
        run: npm run build
