name: Tester

on:
  pull_request:
    branches:
      - main

concurrency:
  group: tester-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create .env File
        shell: bash
        run: |
          tee -a .env <<EOF
          ${{ secrets.FULL_ENV }}
          EOF
      - name: Create service-account-file.json File
        shell: bash
        run: |
          tee -a service-account-file.json <<EOF
          ${{ secrets.SERVICE_ACCOUNT_FILE_JSON }}
          EOF
      - name: Export GOOGLE_APPLICATION_CREDENTIALS Dependency
        shell: bash
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=./service-account-file.json
      - name: Create .env.example File
        shell: bash
        run: |
          tee -a .env.example <<EOF
          ${{ secrets.FULL_ENV_EXAMPLE }}
          EOF
      - name: Echo .env.example
        shell: bash
        run: cat .env.example
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Run Integration Tests
        run: npm run test:e2e